spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
JWT_SECRET_KEY=${JWT_SECRET_KEY}
JWT_EXPIRATION=${JWT_EXPIRATION}
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true